# Generated by Django 6.0.7 on 2026-07-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('phone', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('cover_letter', models.TextField(max_length=1000, verbose_name='Cover Letter')),
                ('cv', models.FileField(upload_to='documents/CVs/', verbose_name='Attach CV')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
