# Generated by Django 6.0.7 on 2026-07-25 14:46

import office.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='tracking_code',
            field=models.CharField(default=office.models.generate_alphanumeric_code, max_length=10, verbose_name='Enter the Code'),
        ),
    ]
