# Generated by Django 6.0.7 on 2026-07-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_career_tracking_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='tracking_code',
        ),
    ]
