# Generated by Django 6.0.7 on 2026-07-25 14:58

import office.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_remove_career_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='tracking_code',
            field=models.CharField(default=office.models.generate_alphanumeric_code, editable=False, max_length=10, unique=True, verbose_name='Enter the Code'),
        ),
    ]
