# Generated by Django 6.0.7 on 2026-07-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_alter_career_tracking_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='tracking_code',
            new_name='random_code',
        ),
    ]
