# Generated by Django 6.0.7 on 2026-07-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_rename_tracking_code_career_random_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='random_code',
        ),
    ]
