# Generated by Django 6.0.7 on 2026-07-25 15:15

import office.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_remove_career_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='random',
            field=models.CharField(default=office.models.generate_alphanumeric_code, editable=False, max_length=10),
        ),
    ]
