# Generated by Django 6.0.7 on 2026-07-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_career_random'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='random',
        ),
    ]
