# Generated by Django 6.0.7 on 2026-07-25 15:42

import office.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0014_remove_career_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='random',
            field=models.CharField(default=office.models.generate_alphanumeric_code, max_length=10, verbose_name='Random Code'),
        ),
    ]
