# Generated by Django 6.0.7 on 2026-07-25 16:29

import office.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0015_career_random'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=150, verbose_name='Subject')),
                ('message', models.TextField(max_length=1000, verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='career',
            name='random',
            field=models.CharField(default=office.models.generate_alphanumeric_code, help_text='This code is used for validation purposes. Please keep it safe.', max_length=10, verbose_name='Validation Code'),
        ),
    ]
