# Generated by Django 6.0.7 on 2026-07-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0016_contact_alter_career_random'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('service', models.CharField(choices=[('Consulting Service', 'Consulting Service'), ('Accounting Service', 'Accounting Service'), ('Audit Service', 'Audit Service'), ('Financial Service', 'Financial Service'), ('Advisory Service', 'Advisory Service'), ('Transaction Service', 'Transaction Service'), ('Taxation Service', 'Taxation Service'), ('Liquidation & Insolvency Service', 'Liquidation & Insolvency Service'), ('bookkeeping', 'Bookkeeping'), ('payroll_services', 'Payroll Services'), ('business_valuation', 'Business Valuation'), ('forensic_accounting', 'Forensic Accounting'), ('management_accounting', 'Management Accounting')], max_length=50, verbose_name='Service')),
                ('details', models.TextField(max_length=1000, verbose_name='Details')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
